title: Your awesome title
author: Sandra
email: sandrai@anzor.co.nz
description: > # this means to ignore newlines until "baseurl:"
  Testing github sites

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
